* rules
RULE #1: focus on the precursors (curiousity, community, experimentation,
expression)

RULE #2: be vigilant for bad outcomes (giving up, phoning it in, dislike for
project)

RULE #3: you are legit

RULE #4: stories, songs, characters are amporphous. do not become discouraged.

RULE #5: fine grained schedules and planning do not work for you, though they
are tempting. 

RULE #6: your gut is an excellent performance tool

RULE #7: anything is possible

RULE #8: embrace the rectangle
* tags
* pin
* tasks
** done
- [X] handle choice nodes
- [X] traverse branch nodes
- [X] traverse set nodes
- [X] improved table editor (implement input* cache on backend)
- [X] edit non-boolean state from the editor
- [X] (4/5) Return node instead of backward connections
- [X] (4/5) ChoiceRepeat node
- [X] (4/6) edit engine options from editor  
- [X] (4/6) show character names in text box 
- [X] (4/7) temporary array thing that keeps track of how many bytes is written to an
  array between the time you instantiate it and a given time
- [X] (4/7) multiple text effects
- [X] (4/7) text effects that work on subset of text
- [X] (4/8) effects in GUI
  - [X] make the pane a bit bigger
  - [X] enter on value does not work
  - [X] if a node has no effects, you have to click off and click on to regenerate the
	table editor and propagate that draw flag to the children
  - [X] print effect type or a name if one is given instead of table index
  - [X] bind effect types between c and lua
  - [X] master list of effect types also
- [X] (4/22) non-developer friendly GUI
  - [X] load / save / run dialogues
- [X] (4/21) fix editor layout flashings
- [X] proper text editor with word wrapping for nodes
  - [X] bind between editor contents and nodes that matter (both ways)
  - [X] arrow key movement** small
- [X] (4/23) text wrap choices
- [X] (4/23) 'if' node -- like a branch node, but doesn't have two branches,
  just gates a node (maybe just a choice) behind a condition
- [X] 4/28 allow non-programmers to add fields to state
- [X] file -> export state, file -> load state

** big
- [ ] update text effect range as string is edited
- [ ] icon heads to see who is talking
- [ ] write the fade in effect
- [ ] fast forward the fade in effect
- [ ] modify node _properties_ based on state
  - for example, prism's name. you don't want to duplicate every node as "one
    where you know prism's name" and "one where you don't"
- [ ] switch to stb_textedit
- [ ] design the menus of the game
  - log of things of intrigue
  - a log where you can type stuff, write down your own log of intrigue
- [ ] implement a basic sound api
** dogfood
- [ ] show in the GUI if a state is not found
- [ ] multiselect nodes in dialogue editor
- [ ] node copy and paste in the editor
- [ ] make lack of entry point very clear
- [ ] need to specify effect ranges from editor, not typing in indices
- [ ] delete effects
- [ ] delete fields from effects
- [ ] word-based text wrapping
- [ ] display made choices
- [ ] copy/paste on text editor
** pie
a really juiced up effects editor. like, one that will live show you what the
effect is as you're doing it. would probably need to render the text to a
texture, unless i could mess with imgui text, would be really lucky if it was
stored as SOA instead of AOS.
* inspiration / reference
fate/stay night ui
https://youtu.be/gAkUUB4B6po?t=551

disco elysium ui
https://youtu.be/N6ETpz_DKWI?t=1854

stardew valley ui
https://youtu.be/2fMwXWSFHA0?list=PLsq7bMZ-qdkb1vfXr5Ty-SYC2LqoAkUt5&t=459

headshot maker
https://picrew.me/image_maker/94097

majikoi and grisaia
* ideas
one of the endings: you don't solve anything and everyone dies

the only reason this colony exists is to serve as a form of genetic preservation
for the seed people, such that they may return at some point and claim
cultivated flesh with static genetics to be recombined into themselves

this idea of what the universe is: static or dynamic. some groups, some engineer
types, view 
* scenes
intro scene:
you awaken, covered in a strange electricity. you struggle to escape the depths
of your mind and return to consciousness. once you awaken, you find someone in
the room with you. they are tall, lanky, they have two eyes made of glass,
wearing spacer coveralls. they seem very preoccupied -- they're going around the room,
scraping things into small containers bandoliered to their body. you try to
move, or speak, but cannot.

eventually, you get out a weak hello. the person perks up and looks in your
direction. you have a very brief back and forth -- more back than forth,
considering your inability to speak. they fumble with their copy of the manual,
finding the right section, before giving a simple, pre-written speech to
welcome bewildered cryopatients from their sleep:
- you have awoken from a long cryogenic sleep
- you may lack fine motor control, ability to speak, etc. but this will wear off
- $PERSON will assist with this, there is much to do to integrate you into
  society

the person seems very absentminded and flighty. you suspect that he's not _with_
you 100% of the time. they think of a small piece of information they need to
compile, and then appear to check out completely -- slumped body, unfocused eye.

you can take this chance to get up. you can put on your coveralls, you can steal
a jar of what he's been collecting, you can put it in the coveralls, if you put
the coveralls on, he discovers you.

you can discuss what he's collecting, although this will flag a small
suspicion.

at this point, you're able to speak. now, you may ask him questions.
- where are you?
- who are you?
- where did i come from?
- where will i live?

he says that you're going to temporarily stay with a prestigious engineering
clan before you can be sorted into your final home. he mentions that they can
kind of eat you alive -- very powerful pod, almost a monarchy of the engineers,
he prefers to stay jacked in, but for your sake here's a contact in our group if
you need to get out. 

you ask him if you can seek him out and talk to him later -- he's preoccupied,
back in his world, he pops back in having clearly not heard you. he asks if
you're as ready to go, and you nod

purpose of this scene:
besides there needing to be a first scene, it needs to do a few things
- player agency. do not monologue at them.
- show the player the wealth of options they have. hint to them how we will
  remember their choices.
- have them understand where they are, who they are, why they are here -- the
  official story
- set up some tension for the next scene (meeting the engineers). set up some
  short-term conflict that will be resolved immediately.

* log
** patrick 3
use some of these short stories as easter eggs.

some kind of bookmaker character who gives odds on when the dome will
malfunction -- keeps highly detailed books. 
** 04/21/2022
- role of the ascetics
- ideas about my group
  - how ma bell may relate to that, or to knowing about that
  - alexander and his crechemates personal investigations, what they want from
    the raid
  - more plot points
- aequimancer plot points


pods are just ways to maintain reproductive logistics. plus unions.

what the fuck is a dentist?

how they deal with water.

aequimancers use a codex instead of the manual -- it's like a software
manual. they have forbidden knowledge of how to manipulate materials. they
prefer to exploit the world. they do not understand chemistry, they just
understand equivalences. alchemy not chemistry.

engineers are catholics. equimancers are eastern religions. what is the nature
of reality.

there is an economy between the aequimancers and the engineers -- they trade
staticism (maintenance vs goods).

most of them find ways to take residual energies out of the ambient environment
-- maybe their voice to augment a technology to provide literal energy, maybe
some ritual self-harm (cutting off tips of fingers) to add to things. this goes
too far, ritual sacrifice.

rainmaking -- they have people who promise that they can coerce the dome to do
certain things, they cannot, just washouts from the equimancers

the movie brazil (terrorist hvac)
dirk gently

motivation for the PC: elder scrolls style getting swept up in a political
conflict? simple necessity driving you to fix the root cause (there is no food,
my friends don't have food, i have to fix this).

enmgies = coexistants
equi = control
ascetics = synthesis

interact with an ascetic. someone who was raised there but washed out, or
antagonistic

ascetics have already merged with the dome

equimancer plot beat: main character finds a guy who is doing meditations who
must do a coming of age ritual. he has failed it several times. he must produce
something of value. he has come to a place of much entropy, like being in the
wild until he can provide something. he brings you back to the coven as his
thing to pass the ritual. the coven call bullshit. they will accept you into
their community, but you have to help him. you explore the environment with him,
and you have to help him collect stuff to make his masterpiece. during this
exploration, you find something very novel.

they barter their stuff for food and basic resources, when there is no food
their value collapses.

what do they want in the raid?
- a holy grail?
- a cache of new raw material
- a new section of the codex
- historical artifacts -- shed more light into the origins of humanity

there is no other life in the dome, no mildew, no gut bacteria.

they think of medicine mechanically, like a flowchart, like a machine. they are
therefore superficially familiar with human anatomy. 
** 04/20/2022
the engineer thread (again).

the ascetics are holed up in their den learning to form a psychic commune with
the dome -- they've figured out how to take certain goods from the aequine
faction and distill it into a crude peyotl which they use to achieve a greater
attenuation with the dome when they make an analog connection to it

ma bell has some (perhaps tangential) association to this group, this aim, but
not the full impact of it. maybe all she knows about are primitive rituals,
rituals that don't actually allow commune with the machine but were a
precursor. she spent some time with them.

first major point of the engineer thread: alexander and his crechemates'
personal investigations into changes that have been happening at the dome. lots
of little clues and small threads you can find hanging around. if you put it
together before the raid, alexander lets you in on what he really wants from the
raid: a canonical, disconnected copy of the Manual from the ascetics.

second plot point is getting close to ma bell. she knows a lot, but it's hard to
squeeze it all out of her. someone who knows as much as she does has to be slow
in trusting. she doesn't have any plans, like joining the ascetics in communion,
but knows enough things to help you form an idea of what they are doing. what
she knows:
** 04/18/2022
   the first ten are where the different pods live. lower numbers are
better. they're more insulated. consider the lower numbers as closer
to the core of the section, the mother base.

each pod is set up like a large communal house. there is a common area
that is led into by seeral hallways. the ceilings are tall, maybe
twelve feet, but lower in the tunnels to seven or eight feet. the
common room has several tunnels that lead to dead ends. these are like
cul-de-sacs where crechemates have rooms. the youngest of a creche
share a room or a set of rooms. the matriarch, and whichever mates are
part of her inner circle, have another, large set of rooms at the end
of a cul-de-sac. 

this innermost room is partly an office, partly a badroom. it is
almost a lair. this is where the business of the pod gets done. not
all pods are laid out so roomily. the less presitigious the pod, the
more rooms must be shared, the less space for the head of the pod to
conduct business. the lowliest pods are just one or two rooms. 

the outermost part of this section is like a docking bay. there is a
main tunnel that connects this section to the sections that
produce. there is a patchwork feeling here. the citizens have
repurposed many of the things the dome produces in order to do some
primitive industrializing. different kinds of boxes, wheels, ramps,
rudimentary items have been assembled into tools that allow them to
move goods back and forth. there are small, busy, loud shops where
specialty foods are sold, trinkets and knick knacks are traded. a
bazaar. 

the loading dock brushes against some of the poorer, outer pods. they
form a U shape. filling in the U is a labrynthine tangle of tunnels
and control rooms that run some critical functions of the dome. air
purification, material decomposition, switching and networking, almost
devops in nature. the glue.

the core of the ascetics does things like: integrity checks,
recordkeeping, canonical copy of the manual, and food production as a
safeguard to their group. 

the equivalents do transmutation. they are the hub for
production. coveralls, capacitors and resistors, tools, dome plates,
they make it all here and ship it (albeit not over a long distance) to
the others. 

so the layout of the dome is like a three-way venn diagram. 
** 04/09/2022
the engineer thread.

you must gain the trust of the engineer family, led by ma bell and
alexander. once you have gained their trust, they tell you about the changes to
the dome's hardware and firmware. alexander is like the boss. he's not a fabled
figure per se, but he's someone who you hear people talk about a lot for the
first part of the game, someone with much power, or much personality, and he's
hyped a lot in your head. the first part is getting to alexander.

you need a low level contact in the engineesr

there is some kind of disturbance between clans, a public disturbance, where you
can meet people from a couple sides. keep it simple: a food dispute. these
disputes never happen, but the recent dome degradations have changed
things. food comes out less often, or more often but in a barely held together
slurry instead of neat balls, or in a less edible form, or in varying
quality. the group that has maintained this subsystem and rations food is being
blamed, and is becoming defensive.

some of the engineers are smuggling out food -- or, maybe it's not just them and
this thread, maybe this is the first key event of the game. you know that in two
days, there's going to be a raid for food. you hear different pieces of it from
every faction. you don't know exactly how it's going to happen, exactly what
each faction is going to do, but you know SOMETHING is going to happen on that
day. when the day comes, it's the air filter incident -- a near-extinction event
caused by what appears to be lack of maintenance but is in fact dome sentience.

the period before the raid is kind of an act 1.5. it's post CROW -- you've
established the basic setting -- but not entirely. you're meeting different
characters from these factions, fleshing out alliances and ideologies.

so what is the engineers' part in this raid?

food, yes, but there is some key piece of engineering in this part of the
dome. maybe this is where the Core is. the engineers, through meticulous
observation, have noticed some mapping between hardware change and change in
reality. they have noticed that on days of search, when the page tables were
being "randomly" modified, certain subsystems were affected, and then those
subsystems fell into a stable state once the correct page had been found.
their table is incomplete, of course. what they need are a set of master
records, handkept records by this monastic third group. this is a set of
records, the details of which are specified in the Manual, that is a sort of
checks and balances from the dome designers to reconcile human experience and
the machinery in the Dome. checks and balances. self consistency. the third
group has restrictions on their lives, again monastically, to prevent the
tainting of the records. to keep their focus sharply on these records if you
will.

these are the records that will fill in their missing data. these are physical
records of observation of the most critical parts of the Dome -- they tie
everything together. i suppose next is what exactly the engineers know, and what
they need to know from the monastic records to draw a conclusion

ok, maybe this is not records -- maybe it also is -- but here is another idea:
this is a quasi-sacred place, the monastery, which stores data from the seed
people.

they might find the binary search algorithm.
they might find historical copies of sectors that don't match the manual

maybe easier to start the other way? what do they have

well, the first thing is that they see the hunting pattern. another thing to
note here is that there are a lot of sectors that are functionally unknown. some
sectors map onto reality explicitly in the manual, but many do not. so when they
observe sectors being hunted, they can't just say -- oh, this is the water
purifying sector, let's check out what's going on there. there is a process of
deduction, many sectors may be hunted at the same time, observations are
imperfect information. so the crux of the information gathering in this step is
to follow several of these threads, figure out what the reality changes are
through lots of questioning and cross referencing.

the first one is confirmation: the bit changing pattern that you see is in fact
a known search algorithm. someone is searching for something.

the engineers' limitation is that they cannot commune with the machine. they
exist purely in the physical world. they can observe physical differences in the
machine, and then the resulting effects in reality, but they do not have access
to anything less grounded than this.

- water
- food
- waste management
- biometrics
- chemical / hormonal management -- allsgood
- subjective reports, audiovisual hallucination, paranoia, irrational anger,
  violent lust

FOOD
easy one to start with is food. so for the engineers, food is a part of the
raid, but it's more of a public facing reason than the true cause. food quality
has gone down to the point of being nearly inedible. food used to come in neat,
self-contained gelatinous spheres which chemically signalled their edibility and
nutrition. they tasted simple, but good, and came in a few varieties to prevent
pallettes from becoming totally stale.

the problem: the thick sacs that encase the gelatinous inside have begun to
degrade. and the taste of the gelatin inside is unimaginably bad. it's a highly
nutritionally dense goo -- probably the size of a tennis ball, and has all
calories and nutritents for the day. to get something so dense, the seed people
had to invent new chemical structures. our tongues were not attuned to these
structures. the point is -- they taste BAD. and now, for everyone outside the
monastery, the only option is to eat this stuff straight.

this in and of itself may be tolerable for some time, but the second problem:
quantity. the dome is producing less, and much of what is produced is lost due
to the nutritious inner not being built to be exposed to air for long periods of
time.

plot thread: discovering the engineers' stores of food, from when they first
noticed these changes about a year ago


AIR COMPOSITION
part of the manual involves making sure that air is being filtered and
recombined as it should be. in the manual, air is divided into component parts
-- not named by name as we would know them, oxygen, nitrogen, but by simple
sequential categories, A, B, C. there are slight variations in these ratios, but
they should maintain within a certain tolerance.

this one is going to be something less concrete, or rather a thread that sticks
in the background until you find something that matches up with it. the gist is
that the ratios of chemicals in the air are used as a form of crowd control, to
induce happiness, or enthusiasm, gumption, restfulness. however, the machine's
blind experimentation with these have disrupted the precise ecosystem of emotion
that the seed people laid out. this is another reason why tensions are so high.

one subplot with this may involve finding the correct bit pattern for some key
sectors involving air composition, and even down to finding how to manipulate
the ratios for specific sectors in specific ways. and then making decisions on
who to pacify, who to enrage


SUBJECTIVE REPORTS
beyond air composition, people also have some sort of chip in their head. or
maybe a special attenuation to magnetic frequencies. something to which the dome
can send commands? is this removing too much agency from these people? maybe
instead of commands, their minds operate on a certain frequency (really
venturing out into handwavey scifi here), and when the dome degenerates it
begins to generate noise on those same channels.

maybe this ties into a phsyical resource, like food, or air. like an ergot
madness thing.

there is a hospital of some sort, unaffiliated with the engineers, from which
you may gain information about the number of people coming in with madness, or
illness.

--

a break from your regularly scheduled programming: i need to produce dialogue
graphs. that is what will move the game forward. this worldbuilding and planning
is necessary, but ultimately i need to make a thing which can be played and
iterated upon.

can i write these threads standalone? here is what is stopping me from doing so:
- what are the places i can be? the people you can talk to are in locations, and
  when you're not talking to people, you are moving between places. what are
  these places? where are people? i need to sketch out how the dome is laid out
- it's hard to jump in the middle when what you have access to and how people
  respond is so heavily influenced by what happens before. how do i write graphs
  that can stand alone and still be incorporated?

idea: you just write these scenarios very simply, with minimal branching. then,
as you write more of these simple scenarios, they generate states which make the
other scenarios more complex. in scenario 2, you find some information that
would open another branch in scenario 1 -- add it.

a good way to flesh out the dome's layout: write, in prose, the scene of
awakening. use some gimmick to where the PC doesn't talk much, maybe cryogenic
fatigue or something, and he is just led around to observe and have things
explained. he is passed off to people from the engineers and 

** patrick 2
the food -- the dome is not producing turkey legs, it's producing a hyper
efficient means of nutrition that biochemically signals that it's food.

there is an economy in this place -- different groups hold different areas that
produce different resources

mechanical vs prayer vs sabotage

CROW - character, relationship, objective, where

web: start with a story board, what are the main threads, which are parallel,
which converge, how do they converge to the ending, what makes them perceive the
ending differently

divergent endings

names: naming people after things in their environment, but don't try too
hard. 3d objects, virtues (what does this culture value)

stories of things from earth that are grossly misrepresented from age
** patrick 1
deep time --

machines themselves are what change, they change the humans or use the humans as
machines

the machine forms this alien form of sentience

the machine is whodunit

the machine is multiple consciousnesses, self sustaining sections.
- the machine was originally built to serve material functions.
- one section is meant to regulate life support -- it begins exploiting people
  to get the materials it needs

some substance that kept the core going that slowly leaked out and caused the
machine to go insane

patron machine entities -- people worship what part of the machine they maintain

more to the environment than sterility and stainless walls -- something for the
player to explore and discover

more conflict! the systems in the machine are getting less efficient -- the
factions fundamentally disagree with the way to solve the problem
- a divine entity, tampering with it would be an affront to god
- a machine, we should try to fix it

machine malfunctions change the ecosystem, if you fix the machine then you
destroy changes

not a slip of paper -- there are not other manufactured things

a one-man cargo cult character who gives you valuable information

dialogue: how people feel and think (about others, their relationships, the
setting, or themselves). vignettes: concepts for characters or setting, then
make the vignettes and dialogue around that (one of the above things). not about
things, how people feel about things.

a workshop of twisted inventions, tried to fuck with the technology in a way
that ended horrifically. some kind of substance to his ideology. arbitrary
matter transmuting? different groups have different things that they've heard
about him. emphasize: there is a clear material benefit to doing what he is
doing, but it is dangerous

each faction thinks that the degradation of the machine is the other faction
fucking with them

cache is a go

if machine is managing resources of humans themselves

do a few draft dialogues of the first or two scene of the game. 
** 03/22/2022
the most important thing is to write the actual mystery. another clue
from disco elysium: you have several major players in the game
(e.g. the union, the company, the police). it is not as simple as
uncovering enough evidence to damn one of these parties. what really
happened is complicated, nuanced, like the assassins in disco
elysium. it's not as simple as finding a main character's fingerprints
on the gun. it's also not a loony out of left field coming in. 

quick idea: let the air filter incident be a big decision
nexus. something that sets up a lot of stuff for later in the
game. it all happens in a rush -- choices you make may save or doom
some characters, pieces of evidence may be lost, characters may see
different things.

so, the question is: who done it? 

the leaders have good incentives to do this. they realize that the
engies are close to building or discovering a ship, or simply close to
a technological breakthrough. they need something to scare people,
reaffirm evangelicism. 

hold on, think about the loony idea again. not to cop off disco too
much, but one thing i actually like about the loony: you can have a
thing happen that is absolutely a spark to a keg, and leaves a massive
unfolding of what actually happened, only to find out it was
chance. it's not what actually happened that's interesting, it's all
of the unpeeling. anyway.

another idea: one of the engies, a low level, does this
accidentally. he confides to leadership afterward, and they lay webs
to obscure him and the group from involvement. 

another idea: also a low level engie, but this time it's because some
mistake was _already_ made. some track left in disassembling the
obelisk that could not be unmade but for drastic measures. 

clue idea: someone is abnormally missing from the location of the
incident, and does not have a good alibi

clue idea: a low-level leader who does some engineering work and may
have had access to the failed component

another idea: infighting between subgroups inside the engies, which
results in the subgroup going rogue and enacting a plan without
signoff from the rest

another idea: staged event by the leaders to reinforce the importance
of orthodox adherence to the maintenance

the world is hermetically sealed. it is a completely closed system. as
far as this civilization is concerned, it is the whole universe. the
discovery that this is not the case is astounding. this relates to the
original idea: without nature around us, the universe would be far
more mysterious

clue idea: the failed part may be composed of several things instead
of one simple thing. find those parts around the world, find
equivalent parts missing from other things, people give hints about
those parts.

a subgroup who are a cross between police, thuggish enforcers, and
fixers. they are the muscle of the leaders. one of them dies in the
incident, but investigation can reveal that he wasn't actually killed
in the incident. these are like the hardy boys. 

another idea: a plant by someone long ago. maybe just regularly long
ago -- a leader, very high up, learned how to subtly edit the
maintenance in such a way that a single part would fail to be serviced
in a non-obvious way. it was a collaboration between the leaders and
the engies, or _one_ leader and engie. the reason ultimately being the
same as that which spawned all of this: survival. ancient documents,
institutional knowledge, something relays the message to the people of
the reality around them. there is something outside. they can reach it
with the technology they have. people are trying that, and it is
nearly an extinction event. these messages are decrypted by a
particularly brilliant citizen or pair of citizens, who decide that
something has to be done to stop it from happening again -- without
leaking the forbidden knowledge.

ancient documents detailing of a past attempt at escape. encrypted, or
encoded. 

(a world full of secrets. not even a surgeon's room is sterile)

encryption schemes, personal computers painstakingly built, messages
placed in the obelisks, scraps of high-tech ultradurable paper used
and reused for milennia

embedding clues to completely arcane puzzles within the
executable. including symbols in the package, a call stack which is
meaningful. open a socket, listen on it until someone sends it a
message. 

that leaves us with three parallel threads:
- the engies plans to deobfuscate the obelisk and use it to generate
  arbitrary matter, ultimately going off-world and thus breaking free
  from the cycle of maintenance
- the leaders plans to activate a mother ship to go off-world, to
  spread humanity and the gospel of man and life as the crux of the
  universe
- unravelling the ancestors plans of having eaten the forbidden fruit
  and trying to put the apple back on the tree by sabotaging the
  citadel

it is kind of unsatisfying to have who done it be totally unrelated to
any main character or group. 

a situation where all of the components to read the ancient documents
are present, but scattered. at the end, you can get two major pieces
-- one from each faction -- that put everything together and unlock
it. 

a good way to structure this: start from the end, which i've already
done. this is the ending. these are the leaves of the tree. then,
start building tree from the leaves. for example -- arbitrary, not
the real plot:
- you must discover the ancestors plan
  - you must gain a private key from the engies
	- you must gain the trust of ma bell
	  - you must do dirty work for ma bell
		- you must hit a certain conversational trigger
	  - you must complete another story objective that is very
        important to the engies
	- you must blackmail prometheus

is it a tree or a graph? not entirely sure, don't care. the point is
you start building threads that lead to your destination, and then
slowly flesh out those threads. add alternate routes that let you skip
to certain nodes of the graph -- multiple ways of getting there, if
you will. 

and try not to let it explode. half proof of concept, here. 

technically, what do i need for the proof of concept?
- push messages to the text box
- scroll through the text box
- make choices
- save and load state
- load the game with an arbitrary state + dialogue

  
4
